version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "security update"
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
    labels:
      - "security update"